### ISSUE TITLE
Schema doesn't work when tested against zuul/zuul

### ISSUE THREAD

**Issue by same-code-different-day** [codesquadnest/zuullint#61] opened 2024-02-25 22:17 UTC
Testing against the opendev zuul project, the tool gives errors for single items needing to be lists. Similar to 48259a9d58486c96bc0316e0dddfeb4374c0d47f, other attributes should be allowed single items over list format.

**Comment by martimmatias** [comment] 2024-04-09 13:54
Hi there, sorry for the very late response.
I was not able to reproduce your issue in the most recent version of Zuul and zuulcilint. Can you tell me which specific files caused an error? Also, could you provide the command output? Maybe it's already fixed!

**Comment by same-code-different-day** [comment] 2024-04-11 23:57
No worries! I appreciate the tool, and the efforts to maintain. I am unfortunately not familiar with modifying jsonschema files, so I was hesitant to make my own PR.

Here is the output of the command

`zuul$ python3 -m zuulcilint .zuul.yaml
.zuul.yaml

Validation error:
File: .zuul.yaml
Message: 'zuul/zuul' is not of type 'array'
Path: [18, 'job', 'allowed-projects']
Schema Path: ['items', 'properties', 'job', 'properties', 'allowed-projects', 'type']


Validation error:
File: .zuul.yaml
Message: 'zuul/zuul' is not of type 'array'
Path: [19, 'job', 'allowed-projects']
Schema Path: ['items', 'properties', 'job', 'properties', 'allowed-projects', 'type']


Validation error:
File: .zuul.yaml
Message: 'zuul/zuul' is not of type 'array'
Path: [20, 'job', 'allowed-projects']
Schema Path: ['items', 'properties', 'job', 'properties', 'allowed-projects', 'type']


Checking for duplicate jobs
No duplicate jobs found

Checking for inexistent nodesets
ubuntu-jammy

Warnings
Total warnings: 1

Inexistent nodeset warnings:
Found 1 inexistent nodesets
ubuntu-jammy

Failed

Total errors: 3
YAML validation errors: 3`

Here is what I think are the relevant parts of my environment:
`zuul$ python3 --version
Python 3.10.12

zuul$ python3 -m pip list | grep zuulcilint
zuulcilint                0.2.5

zuul$ git log -1
commit 59ca809a9e8b722bd25e17508710821c2e27e9d0 (HEAD -> master, origin/master, origin/HEAD)
Merge: afcbe6559 505253bed
Author: Zuul <zuul@review.opendev.org>
Date:   Wed Apr 10 22:48:09 2024 +0000

    Merge "Handle artifacts created by non change refs"`

**Comment by martimmatias** [comment] 2024-04-16 11:30
Thank you for the comprehensive logs. I have identified the issue.
In my PR, the allowed-projects property of job objects accepts single string values as well.

**Comment by pmpbaptista** [comment] 2024-04-18 23:33
Closing issue.
Fix is available in version 0.2.6 which is now live.

Thanks for your effort
@martimmatias 
@same-code-different-day

**Closed as completed by pmpbaptista** 2024-04-18 23:33 UTC
